#version 460 core

layout(local_size_x = 256) in;

//  64 bytes - layout matches C++ `Vertex` (vec3 + pad, vec3 + pad, vec4, vec2, pad[2])
struct Vertex {
	vec3 position;
	float pad1; // match CPU padding
	vec3 normal;
	float pad2; // match CPU padding
	vec4 color;
	vec2 texCoords;
	float pad[2];
};

layout(std430, binding = 0) buffer Vertices {
    Vertex vertices[];
};


uniform float craterDepth;
uniform float craterSteepness;
uniform float craterWidth;

uniform float rimSteepness;
uniform float rimWidth;
uniform float smoothingK;

//  32 bytes
struct Crater {
	vec4 position; // 16
	float size;
	float height;
	float pad[2]; // 16
};

layout(std430, binding = 1) buffer Craters{
	Crater craters[];
};



// Variables
uniform int resolution;
uniform float radius;
uniform int numVerts;

// craters
uniform int numCraters;

// noise
uniform vec3 noiseCentre;
uniform int numLayers;
uniform float noiseStrength;
uniform float noiseBaseFrequency;
uniform float noiseHeightShift;

// coloring
uniform vec4 peakColor;
uniform vec4 surfaceColor;


// CRATERS 
float smin( float a, float b, float k )
{
    k *= 1.0;
    float r = exp2(-a/k) + exp2(-b/k);
    return -k*log2(r);
}

float CraterHeight(float x, Crater crater) {
	float result = 0.0;

	float concave = (pow(x / craterWidth, craterSteepness) * craterDepth) - (craterDepth - 1);
	concave = min(concave, 1);
	concave = smin(concave, -craterDepth / 2, -smoothingK);

	float rim = pow(1 - ((x - craterWidth) / rimWidth), rimSteepness);
	rim = max(rim, 0);

	result = smin(rim, concave, smoothingK) * crater.height;

	return result;
}


float CraterInfluence(Vertex vert){
	float ci = 0.0;
	for (int i = 0; i < numCraters; i++){
		float dist = distance(vert.position, craters[i].position.xyz);

		if(dist / craters[i].size <= (craterWidth + rimWidth) * 1.2){
			ci += CraterHeight(dist / craters[i].size, craters[i]);
		}
	};

	return ci;
}


// BASIC NOISE
float hash(float n) { return fract(sin(n) * 1e4); }
float hash(vec2 p) { return fract(1e4 * sin(17.0 * p.x + p.y * 0.1) * (0.1 + abs(sin(p.y * 13.0 + p.x)))); }

float noise(float x) {
	float i = floor(x);
	float f = fract(x);
	float u = f * f * (3.0 - 2.0 * f);
	return mix(hash(i), hash(i + 1.0), u);
}

float noise(vec2 x) {
	vec2 i = floor(x);
	vec2 f = fract(x);

	// Four corners in 2D of a tile
	float a = hash(i);
	float b = hash(i + vec2(1.0, 0.0));
	float c = hash(i + vec2(0.0, 1.0));
	float d = hash(i + vec2(1.0, 1.0));

	vec2 u = f * f * (3.0 - 2.0 * f);
	return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float noise(vec3 x) {
	const vec3 step = vec3(110, 241, 171);

	vec3 i = floor(x);
	vec3 f = fract(x);
 
	
    float n = dot(i, step);

	vec3 u = f * f * (3.0 - 2.0 * f);
	return mix(mix(mix( hash(n + dot(step, vec3(0, 0, 0))), hash(n + dot(step, vec3(1, 0, 0))), u.x),
                   mix( hash(n + dot(step, vec3(0, 1, 0))), hash(n + dot(step, vec3(1, 1, 0))), u.x), u.y),
               mix(mix( hash(n + dot(step, vec3(0, 0, 1))), hash(n + dot(step, vec3(1, 0, 1))), u.x),
                   mix( hash(n + dot(step, vec3(0, 1, 1))), hash(n + dot(step, vec3(1, 1, 1))), u.x), u.y), u.z);
}

float NoiseInfluence(Vertex vert){
	float ni = 0.0;

	float noiseFreq = noiseBaseFrequency;
	float strength = noiseStrength;

	float noiseRemap = 0.0;

	for(int i = 0; i < numLayers; i++){
		float d = (noise((vec3(vert.position) + (noiseCentre * radius)) * noiseFreq));
		ni += d * strength;
		noiseFreq *= 1.5;
		noiseRemap += strength;
		strength *= 0.5;
	}

	ni += (noiseHeightShift) - (noiseRemap / 2);

	return ni;
}


// MAIN
vec3 GetPosition(vec3 dir){
	float d = 0.0;

	Vertex v;
	v.position = dir * radius;
	v.normal = dir;

	d += NoiseInfluence(v);
	d += CraterInfluence(v);

	return (v.position + dir * d);
};

vec3 CalculateNormal(vec3 dir, vec3 pos){
	vec3 helper = abs(dir.y) > 0.99 ? vec3(1,0,0) : vec3(0,1,0);
	vec3 right = normalize(cross(helper, dir));
	vec3 forward = cross(dir, right);

	float eps = 0.001;

	// sample nearby positions
	vec3 px = GetPosition(normalize(dir + right * eps));
	vec3 py = GetPosition(normalize(dir + forward * eps));

	// compute normal
	vec3 normal = normalize(cross(px - pos, py - pos));

	return normal;
};

void main(){
	uint idx = gl_GlobalInvocationID.x;

	uint vertID = idx;
	if (vertID >= numVerts)
		return;

	Vertex vert = vertices[vertID];
	
	vec3 dir = normalize(vert.position);
	vec3 pos = GetPosition(dir);
	vec3 normal = CalculateNormal(dir, pos);

	// Colorising
	float col_blend = (length(pos) - radius);

	vec4 color;
	color = vec4(col_blend, col_blend, col_blend, 1.0);
	color = mix(surfaceColor, peakColor, col_blend);
	color = clamp(color, surfaceColor, peakColor);

	vert.position = pos;
	vert.normal = normal;
	vert.color = color;

	// assign it back
	vertices[vertID] = vert;
}