#version 460 core

layout(local_size_x = 256) in;






// Create model of the solar system of when pangea existed
//

///////////////////////////////////////////////////////////////
// Base Settings
///////////////////////////////////////////////////////////////



//  64 bytes - layout matches C++ `Vertex` (vec3 + pad, vec3 + pad, vec4, vec2, pad[2])
struct Vertex {
	vec3 position;
	float pad1; // match CPU padding
	vec3 normal;
	float pad2; // match CPU padding
	vec2 texCoords;
	float pad[2];
};

layout(std430, binding = 0) buffer Vertices {
    Vertex vertices[];
};


// Variables
uniform int resolution;
uniform float radius;
uniform int numVerts;


///////////////////////////////////////////////////////////////
// Craters
///////////////////////////////////////////////////////////////



uniform float craterDepth;
uniform float craterSteepness;
uniform float craterWidth;

uniform float craterHeight;

uniform float rimSteepness;
uniform float rimWidth;
uniform float smoothingK;
uniform int numCraters;

//  32 bytes
struct Crater {
	vec4 position; // 16
	float size;
	float height;
	float pad[2]; // 16
};

layout(std430, binding = 1) buffer Craters{
	Crater craters[];
};


float smin( float a, float b, float k )
{
    k *= 1.0;
    float r = exp2(-a/k) + exp2(-b/k);
    return -k*log2(r);
}


float CraterHeight(float x, Crater crater) {
	float result = 0.0;

	float concave = (pow(x / craterWidth, craterSteepness) * craterDepth) - (craterDepth - 1);
	concave = min(concave, 1);
	concave = smin(concave, -craterDepth / 2, -smoothingK);

	float rim = pow(1 - ((x - craterWidth) / rimWidth), rimSteepness);
	rim = max(rim, 0);

	result = smin(rim, concave, smoothingK) * crater.height;

	return result;
}


float CraterInfluence(Vertex vert){
	float ci = 0.0;
	for (int i = 0; i < numCraters; i++){
		float dist = distance(vert.position, craters[i].position.xyz);

		if(dist / craters[i].size <= (craterWidth + rimWidth) * 1.2){
			ci += CraterHeight(dist / craters[i].size, craters[i]) * craterHeight * (dist / craters[i].size);
		}
	};

	return ci;
}



///////////////////////////////////////////////////////////////
// Noise
///////////////////////////////////////////////////////////////

uniform int numNoiseLayers;

struct NoiseLayer {
	vec3 centre;
	int type; // 0 = perlin, 1 = voronoi
	float frequency;
	float intensity;
	int numLayers;
	float frequencyFactor;
	float intensityFactor;
	float heightShift;
	float wobble;
	float power;
};

layout(std430, binding = 2) buffer NoiseLayers {
    NoiseLayer noiseLayers[];
};


// ===== PERLIN ===== 

float hash(float n) { return fract(sin(n) * 1e4); }
float hash(vec2 p) { return fract(1e4 * sin(17.0 * p.x + p.y * 0.1) * (0.1 + abs(sin(p.y * 13.0 + p.x)))); }
vec3 hash(vec3 p) {   return fract(sin(vec3(dot(p, vec3(1.0, 57.0, 113.0)), dot(p, vec3(57.0, 113.0, 1.0)), dot(p, vec3(113.0, 1.0, 57.0)))) * 43758.5453); }

float noise(float x) {
	float i = floor(x);
	float f = fract(x);
	float u = f * f * (3.0 - 2.0 * f); // good way to do seed??
	return mix(hash(i), hash(i + 1.0), u);
}

float noise(vec2 x) {
	vec2 i = floor(x);
	vec2 f = fract(x);

	// Four corners in 2D of a tile
	float a = hash(i);
	float b = hash(i + vec2(1.0, 0.0));
	float c = hash(i + vec2(0.0, 1.0));
	float d = hash(i + vec2(1.0, 1.0));

	vec2 u = f * f * (3.0 - 2.0 * f);
	return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float PerlinNoise(vec3 x) {
	const vec3 step = vec3(110, 241, 171);

	vec3 i = floor(x);
	vec3 f = fract(x);
 
	
    float n = dot(i, step);

	vec3 u = f * f * (3.0 - 2.0 * f);
	float result = mix(mix(mix( hash(n + dot(step, vec3(0, 0, 0))), hash(n + dot(step, vec3(1, 0, 0))), u.x),
                   mix( hash(n + dot(step, vec3(0, 1, 0))), hash(n + dot(step, vec3(1, 1, 0))), u.x), u.y),
               mix(mix( hash(n + dot(step, vec3(0, 0, 1))), hash(n + dot(step, vec3(1, 0, 1))), u.x),
                   mix( hash(n + dot(step, vec3(0, 1, 1))), hash(n + dot(step, vec3(1, 1, 1))), u.x), u.y), u.z);

	return result;
}


// https://github.com/MaxBittker/glsl-voronoi-noise/blob/master/3d.glsl
float VoronoiNoise(vec3 x){
	vec3 p = floor(x);
	vec3 f = fract(x);

	float id = 0.0;
	vec2 res = vec2(100.0);
	for (int k = -1; k <= 1; k++) {
		for (int j = -1; j <= 1; j++) {
			for (int i = -1; i <= 1; i++) {
				vec3 b = vec3(float(i), float(j), float(k));
				vec3 r = vec3(b) - f + hash(p + b);
				float d = dot(r, r);

				float cond = max(sign(res.x - d), 0.0);
				float nCond = 1.0 - cond;

				float cond2 = nCond * max(sign(res.y - d), 0.0);
				float nCond2 = 1.0 - cond2;

				id = (dot(p + b, vec3(1.0, 57.0, 113.0)) * cond) + (id * nCond);
				res = vec2(d, res.x) * cond + res * nCond;

				res.y = cond2 * d + nCond2 * res.y;
			}
		}
	}

	return pow(res.x, 3);
}

float NoiseInfluence(Vertex vert) {
    float total_noise = 0.0;
	
	for (int i = 0; i < numNoiseLayers; i++){
		NoiseLayer currentLayer = noiseLayers[i];

		// Precompute base position for noise
		vec3 pos = vec3(vert.position) + (currentLayer.centre * radius);


		float current_noise = 0.0;           // Accumulated noise

		float freq = currentLayer.frequency;
		float strength = currentLayer.intensity;
		float totalStrength = 0.0; // For normalization

		for (int i = 0; i < currentLayer.numLayers; i++) {
			// Sample noise at current frequency

			float randx = noise(currentLayer.wobble);
			float randy = noise(randx);
			float randz = noise(randy);

			vec3 wobble_noise = normalize(vec3((2 * randx) - 1, (2*randy) - 1, (2*randz) - 1)) * currentLayer.wobble * radius;

			float n = 0;
			if(currentLayer.type == 0){
				n = PerlinNoise((pos + wobble_noise) * freq);
			}else if (currentLayer.type == 1){
				n = VoronoiNoise((pos + wobble_noise) * freq);
			}

			// Accumulate weighted noise
			current_noise += n * strength;

			// Track total amplitude
			totalStrength += strength;

			// Prepare for next layer
			freq *= currentLayer.frequencyFactor;  // Increase frequency (smaller features)
			strength *= currentLayer.intensityFactor;   // Decrease amplitude (finer details contribute less)
		}

		// Normalize and apply height shift
		// current_noise = current_noise - (totalStrength / 2.0) + currentLayer.heightShift;
		current_noise += currentLayer.heightShift;

		total_noise += current_noise;
	}


    // Ensure non-negative output
    return total_noise;
}







///////////////////////////////////////////////////////////////
// Main
///////////////////////////////////////////////////////////////




vec3 GetPosition(vec3 dir){
	float d = 0.0;

	Vertex v;
	v.position = dir * radius;
	v.normal = dir;

	d += NoiseInfluence(v);
	d += CraterInfluence(v);

	return (v.position + dir * d);
};

vec3 CalculateNormal(vec3 dir, vec3 pos){
	vec3 helper = abs(dir.y) > 0.99 ? vec3(1,0,0) : vec3(0,1,0);
	vec3 right = normalize(cross(helper, dir));
	vec3 forward = cross(dir, right);

	float eps = 0.001;

	// sample nearby positions
	vec3 px = GetPosition(normalize(dir + right * eps));
	vec3 py = GetPosition(normalize(dir + forward * eps));

	// compute normal
	vec3 normal = normalize(cross(px - pos, py - pos));

	return normal;
};


void main(){
	uint idx = gl_GlobalInvocationID.x;

	uint vertID = idx;
	if (vertID >= numVerts)
		return;

	Vertex vert = vertices[vertID];
	
	vec3 dir = normalize(vert.position);
	vec3 pos = GetPosition(dir);
	vec3 normal = CalculateNormal(dir, pos);

	// Colorising
	float col_blend = (length(pos) - radius);

	vec4 color;
	color = vec4(col_blend, col_blend, col_blend, 1.0);

	vert.position = pos;
	vert.normal = normal;

	// assign it back
	vertices[vertID] = vert;
}